Datatables language
HB9HIL/Cloudlog pull request #51
Opened 2024-01-02 10:59 UTC by HB9HIL

2024-01-02 11:10 UTC, int2001 commented on application/views/interface_assets/footer.php
> +        console.log(datatables_language_url);
Remove dbg-output

2024-01-02 11:10 UTC, int2001 approved these changes
Working. Bug is away.
Remove dbg-output and merge?!

2024-01-02 11:13 UTC, HB9HIL commented on application/views/interface_assets/footer.php
> +        console.log(datatables_language_url);
ah yes

2024-01-02 11:38 UTC, HB9HIL commented
> Working. Bug is away. Remove dbg-output and merge?!

dbg-output is removed

and no, 
not merge ready yet. Still some datatables are missing and not working properly. 

we use the Datatable JS around 70 times in the complete Code

2024-01-02 11:43 UTC, int2001 commented
assign review when finished. i'll test all datatables afterwards. Tested only LBA so far

2024-01-04 19:22 UTC, HB9HIL reviewed
I think this one is ready 2 merge. I compared with Tamh's Code. Is is just using another name for the function and using a faulty code in footer. My version is working properly as I can see that. 

Important to say, that the datatable languages in the public view's like public log and oqrs are hardcoded to english as this is international.

2024-01-05 06:25 UTC, int2001 requested changes
working tested:
- Bandlist (DXCluster)
- Bands
- Anonymous Slug OQRS
- Some random Award-Pages

Not working:
- oqrs.js (Throwing JS: `jquery-3.3.1.min.js:2  GET https://l[url]/index.php/assets/json/datatables_languages/en-GB.json 404 (Not Found)` - invoked by L74
- Anonymous Slug Dashboard - function `getDataTablesLanguageUrl` not found
- Anonymous Slug Gridsquares - function `getDataTablesLanguageUrl` not found

2024-01-06 09:32 UTC, HB9HIL commented
> working tested:
> 
> * Bandlist (DXCluster)
> * Bands
> * Anonymous Slug OQRS
> * Some random Award-Pages
> 
> Not working:
> 
> * oqrs.js (Throwing JS: `jquery-3.3.1.min.js:2  GET https://l[url]/index.php/assets/json/datatables_languages/en-GB.json 404 (Not Found)` - invoked by L74
> * Anonymous Slug Dashboard - function `getDataTablesLanguageUrl` not found
> * Anonymous Slug Gridsquares - function `getDataTablesLanguageUrl` not found

I disabled the multilanguage for datatables in the public views, as the default is english and as we do not have a selectable language in the public views now it should stay english.

2024-01-06 12:51 UTC, merged